import type { Metadata } from "next";
import "../styles/globals.css";
import { pretendardSans } from "../fonts/variables";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendardSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
